### ISSUE TITLE
Plugin doesn't installed.

### ISSUE THREAD

**Issue by panda919** [pritasam/react-native-arcore#1]
I tried npm install react-native-arcore --save
But only package.json file is download into node_modules/react-native-arcore folder.
Main Kernal doesn;t downloaded .!!!

**Comment by bjdash** [comment]
+1

**Comment by pritasam** [comment]
If is fixed now..Plugin is using latest version of ARCORE now

**Comment by pritasam** [comment]
If is fixed now..Plugin is using latest version of ARCORE now
