### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ismailgultekin** [pritasam/react-native-arcore#2]
board packages - npm package name -v?
react-native : version 6.5.0
react-native-arcore: version 6.5.0

But package.json:

"dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-arcore": "0.0.1",
    "react-native-arkit": "^0.9.0"
  }

1) node_modules: No folders in your folder(react-native-arcore)

2) MainActivity.java  getPackages() NO ?

**Comment by pritasam** [comment]
Hi @ismailgultekin  I am updating the library soon(Today)...It will have support for new ARCORE version and can work with minimum efforts

**Comment by pritasam** [comment]
It is fixed now

**Comment by pritasam** [comment]
If is fixed now..Plugin is using latest version of ARCORE now
